services:
  # PostgreSQL for User Service
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql
    networks:
      - ecommerce-net

  # PostgreSQL for Product Service
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # External: 5433, Internal: 5432
    volumes:
      - product_data:/var/lib/postgresql
    networks:
      - ecommerce-net

volumes:
  user_data:
  product_data:

networks:
  ecommerce-net:
    driver: bridge